### ISSUE TITLE
Vendor/bin/phpstan-php-config not created

### ISSUE THREAD

**Issue by gertvdb** [symplify/phpstan-php-config#1]
The documentation says to use the command :

```
vendor/bin/phpstan-php-config
```

But the bin file is not present in vendor/bin

```
"vendor/symplify/phpstan-php-config/bin/phpstan-php-config convert phpstan.php --output-file phpstan-converted.neon"
```

Does work so i guess it's just adding a "bin" section to composer.json?

**Comment by TomasVotruba** [comment]
Hi, thansk for reporting!

> Does work so i guess it's just adding a "bin" section to composer.json?

That's the way to go :+1: 

This is just split repository, the main repository to edit file is here: https://github.com/symplify/symplify
